import { utilService } from '../../../services/util.service.js'

export const demoNotes = [
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: true,
    style: { backgroundColor: '#ffadad' },
    info: {
      title: 'Mountain View',
      url: 'https://picsum.photos/1000/1000?random=1',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: true,
    style: { backgroundColor: '#ffd6a5' },
    info: {
      title: 'Daily Tasks',
      todos: [
        { id: utilService.makeId(3), txt: 'Check emails', isDone: false },
        { id: utilService.makeId(3), txt: 'Write report', isDone: true },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: true,
    style: { backgroundColor: '#fdffb6' },
    info: { title: 'Meeting Notes', txt: 'Discuss quarterly goals' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: false,
    style: { backgroundColor: '#caffbf' },
    info: {
      title: 'Ocean Sunset',
      url: 'https://picsum.photos/1000/1000?random=2',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: false,
    style: { backgroundColor: '#9bf6ff' },
    info: {
      title: 'Shopping List',
      todos: [
        { id: utilService.makeId(3), txt: 'Milk', isDone: true },
        { id: utilService.makeId(3), txt: 'Bread', isDone: false },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: false,
    style: { backgroundColor: '#a0c4ff' },
    info: { title: 'Reminder', txt: 'Call the bank' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: false,
    style: { backgroundColor: '#bdb2ff' },
    info: {
      title: 'City Skyline',
      url: 'https://picsum.photos/1000/1000?random=3',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: false,
    style: { backgroundColor: '#ffc6ff' },
    info: {
      title: 'Work Tasks',
      todos: [
        { id: utilService.makeId(3), txt: 'Finish coding', isDone: false },
        { id: utilService.makeId(3), txt: 'Send invoice', isDone: false },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: false,
    style: { backgroundColor: '#ffadad' },
    info: { title: 'Ideas', txt: 'New app concept' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: true,
    style: { backgroundColor: '#ffd6a5' },
    info: {
      title: 'Forest Path',
      url: 'https://picsum.photos/1000/1000?random=4',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: false,
    style: { backgroundColor: '#fdffb6' },
    info: {
      title: 'Gym Routine',
      todos: [
        { id: utilService.makeId(3), txt: 'Push-ups', isDone: true },
        { id: utilService.makeId(3), txt: 'Run 3km', isDone: false },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: false,
    style: { backgroundColor: '#caffbf' },
    info: { title: 'Books to Read', txt: 'Finish chapter 5' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: false,
    style: { backgroundColor: '#9bf6ff' },
    info: {
      title: 'Desert Dunes',
      url: 'https://picsum.photos/1000/1000?random=5',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: true,
    style: { backgroundColor: '#ffb6b6' },
    info: {
      title: 'Weekend Tasks',
      todos: [
        { id: utilService.makeId(3), txt: 'Laundry', isDone: false },
        { id: utilService.makeId(3), txt: 'Grocery', isDone: true },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: false,
    style: { backgroundColor: '#ffd6a5' },
    info: { title: 'Notes', txt: 'Prepare presentation' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: false,
    style: { backgroundColor: '#fdffb6' },
    info: { title: 'Beach', url: 'https://picsum.photos/1000/1000?random=6' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: false,
    style: { backgroundColor: '#caffbf' },
    info: {
      title: 'Study Plan',
      todos: [
        { id: utilService.makeId(3), txt: 'Math exercises', isDone: false },
        { id: utilService.makeId(3), txt: 'Read articles', isDone: true },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: true,
    style: { backgroundColor: '#9bf6ff' },
    info: { title: 'Motivation', txt: 'Keep learning!' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: false,
    style: { backgroundColor: '#a0c4ff' },
    info: { title: 'River', url: 'https://picsum.photos/1000/1000?random=7' },
  },
]
