import { utilService } from '../../../services/util.service.js'

export const colors = {
  none: '#ffffffff',
  coral: '#faafa8',
  peach: '#f39f76',
  sand: '#fff8b8',
  mint: '#e2f6d3',
  sage: '#b4ddd3',
  fog: '#d4e4ed',
  storm: '#aeccdc',
  dusk: '#d3bfdb',
  blossom: '#f6e2dd',
  clay: '#e9e3d4',
  chalk: '#efeff1',
}

export const demoNotes = [
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'video',
    isPinned: true,
    style: { backgroundColor: colors.none },
    info: {
      title: 'Somewhere over the rainbow',
      url: 'assets/video/somewhere-over-the-rainbow.mp4',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: true,
    style: { backgroundColor: colors.coral },
    info: {
      title: 'Daily Tasks',
      todos: [
        { id: utilService.makeId(3), txt: 'Check emails', isDone: false },
        { id: utilService.makeId(3), txt: 'Write report', isDone: true },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: true,
    style: { backgroundColor: colors.sage },
    info: { title: 'Meeting Notes', txt: 'Discuss quarterly goals' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: false,
    style: { backgroundColor: colors.storm },
    info: {
      title: 'Ocean Sunset',
      url: 'https://picsum.photos/1000/1000?random=2',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: false,
    style: { backgroundColor: colors.none },
    info: {
      title: 'Shopping List',
      todos: [
        { id: utilService.makeId(3), txt: 'Milk', isDone: true },
        { id: utilService.makeId(3), txt: 'Bread', isDone: false },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: false,
    style: { backgroundColor: colors.chalk },
    info: { title: 'Reminder', txt: 'Call the bank' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: false,
    style: { backgroundColor: colors.mint },
    info: {
      title: 'City Skyline',
      url: 'https://picsum.photos/1000/1000?random=3',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: false,
    style: { backgroundColor: colors.none },
    info: {
      title: 'Work Tasks',
      todos: [
        { id: utilService.makeId(3), txt: 'Finish coding', isDone: false },
        { id: utilService.makeId(3), txt: 'Send invoice', isDone: false },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: false,
    style: { backgroundColor: colors.sand },
    info: { title: 'Ideas', txt: 'New app concept' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'video',
    isPinned: false,
    style: { backgroundColor: colors.coral },
    info: {
      title: 'Pizzaaa',
      url: 'assets/video/pizza.mp4',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: false,
    style: { backgroundColor: colors.none },
    info: {
      title: 'Gym Routine',
      todos: [
        { id: utilService.makeId(3), txt: 'Push-ups', isDone: true },
        { id: utilService.makeId(3), txt: 'Run 3km', isDone: false },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: false,
    style: { backgroundColor: colors.none },
    info: { title: 'Books to Read', txt: 'Finish chapter 5' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: false,
    style: { backgroundColor: colors.peach },
    info: {
      title: 'Desert Dunes',
      url: 'https://picsum.photos/1000/1000?random=5',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: true,
    style: { backgroundColor: colors.peach },
    info: {
      title: 'Weekend Tasks',
      todos: [
        { id: utilService.makeId(3), txt: 'Laundry', isDone: false },
        { id: utilService.makeId(3), txt: 'Grocery', isDone: true },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: false,
    style: { backgroundColor: colors.none },
    info: { title: 'Notes', txt: 'Prepare presentation' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'video',
    isPinned: true,
    style: { backgroundColor: colors.fog },
    info: {
      title: 'My cute cow',
      url: 'assets/video/cow.mp4',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: false,
    style: { backgroundColor: colors.clay },
    info: {
      title: 'Study Plan',
      todos: [
        { id: utilService.makeId(3), txt: 'Math exercises', isDone: false },
        { id: utilService.makeId(3), txt: 'Read articles', isDone: true },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: true,
    style: { backgroundColor: colors.dusk },
    info: { title: 'Motivation', txt: 'Keep learning!' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: false,
    style: { backgroundColor: colors.none },
    info: { title: 'River', url: 'https://picsum.photos/1000/1000?random=7' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: true,
    style: { backgroundColor: colors.mint },
    info: {
      title: 'Morning Routine',
      todos: [
        { id: utilService.makeId(3), txt: 'Meditate', isDone: false },
        { id: utilService.makeId(3), txt: 'Drink water', isDone: true },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: true,
    style: { backgroundColor: colors.chalk },
    info: { title: 'Quote', txt: 'Progress is progress' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: true,
    style: { backgroundColor: colors.sage },
    info: {
      title: 'Forest Path',
      url: 'https://picsum.photos/1000/1000?random=21',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: true,
    style: { backgroundColor: colors.peach },
    info: {
      title: 'House Chores',
      todos: [
        { id: utilService.makeId(3), txt: 'Vacuum floors', isDone: false },
        { id: utilService.makeId(3), txt: 'Wash dishes', isDone: true },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: true,
    style: { backgroundColor: colors.fog },
    info: { title: 'Learning Goals', txt: 'Finish React hooks today' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: true,
    style: { backgroundColor: colors.blossom },
    info: {
      title: 'Cute Cat',
      url: 'https://picsum.photos/1000/1000?random=22',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: false,
    style: { backgroundColor: colors.storm },
    info: { title: 'Reminders', txt: 'Renew subscription' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: false,
    style: { backgroundColor: colors.coral },
    info: {
      title: 'Highland Cow',
      url: 'https://picsum.photos/1000/1000?random=23',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'todo',
    isPinned: false,
    style: { backgroundColor: colors.sand },
    info: {
      title: 'Shopping',
      todos: [
        { id: utilService.makeId(3), txt: 'Eggs', isDone: false },
        { id: utilService.makeId(3), txt: 'Tomatoes', isDone: true },
      ],
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: false,
    style: { backgroundColor: colors.dusk },
    info: { title: 'Plan', txt: 'Finish the Keep clone by Sunday' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: true,
    style: { backgroundColor: colors.mint },
    info: { title: 'Focus', txt: 'One task at a time' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: true,
    style: { backgroundColor: colors.peach },
    info: {
      title: 'Mountain Lake',
      url: 'https://picsum.photos/1000/1000?random=31',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: true,
    style: { backgroundColor: colors.sand },
    info: { title: 'Checklist', txt: 'Review code before commit' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'photo',
    isPinned: true,
    style: { backgroundColor: colors.blossom },
    info: {
      title: 'Cozy Room',
      url: 'https://picsum.photos/1000/1000?random=32',
    },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'text',
    isPinned: true,
    style: { backgroundColor: colors.storm },
    info: { title: 'Ideas', txt: 'Try adding drag & drop to notes' },
  },
]
