import { utilService } from '../../../services/util.service.js'

export const demoNotes = [
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: true,
    style: { backgroundColor: '#ffadad' },
    info: { title: 'Shopping List', txt: 'Groceries: milk, bread, coffee' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: true,
    style: { backgroundColor: '#ffd6a5' },
    info: { title: 'Workout', txt: 'Workout plan for today' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: true,
    style: { backgroundColor: '#fdffb6' },
    info: { title: 'Birthday Reminder', txt: 'Remember Mom’s birthday' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: true,
    style: { backgroundColor: '#caffbf' },
    info: { title: 'Bug Fix', txt: 'Fix the login bug' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: true,
    style: { backgroundColor: '#9bf6ff' },
    info: { title: 'Weekly Plan', txt: 'Plan next week’s tasks' },
  },

  // --- 15 unpinned ---
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#a0c4ff' },
    info: { title: 'Pet Care', txt: 'Buy dog food' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#bdb2ff' },
    info: { title: 'Study', txt: 'Learn Flexbox' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#ffc6ff' },
    info: { title: 'Meeting', txt: 'Meeting at 14:00' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#ffadad' },
    info: { title: 'Chores', txt: 'Clean the house' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#ffd6a5' },
    info: { title: 'Learning', txt: 'Watch JS tutorial' },
  },

  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#fdffb6' },
    info: { title: 'Bills', txt: 'Pay electricity bill' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#caffbf' },
    info: { title: 'Health', txt: 'Book dentist appointment' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#9bf6ff' },
    info: { title: 'Project Ideas', txt: 'Ideas for new project' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#a0c4ff' },
    info: { title: 'Mindfulness', txt: 'Meditation for 10 min' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#bdb2ff' },
    info: { title: 'Family', txt: 'Call Grandma' },
  },

  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#ffc6ff' },
    info: { title: 'CSS Fix', txt: 'Fix CSS alignment' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#ffadad' },
    info: { title: 'Reading', txt: 'Finish reading chapter 3' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#ffd6a5' },
    info: { title: 'Plants', txt: 'Water the plants' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#fdffb6' },
    info: { title: 'Organization', txt: 'Organize the closet' },
  },
  {
    id: utilService.makeId(4),
    createdAt: utilService.getRandomTimestamp(),
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#caffbf' },
    info: { title: 'Cooking', txt: 'Try new recipe' },
  },
]
